---
- name: Deploy git_pg-promise app
  hosts: fron_pg-promise
  become: yes
  pre_tasks:
    - name: Update repositories cache
      package:
        update_cache: yes
  roles:
    - role: front_pg-promise
