---
- name: Deploy git_pg-promise app
  hosts: front_pg_promise
  become: yes
  pre_tasks:
    - name: Update repositories cache
      package:
        update_cache: yes
  roles:
    - role: './roles/front_pg-promise'
