---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debianpg
    image: "geerlingguy/docker-debian10-ansible"
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      ask_vault_pass: true
verifier:
  name: ansible
  lint: |
    set -e
    yamllint .

