---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian_pg
    image: "geerlingguy/docker-debian10-ansible"
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      ask_vault_pass: true
verifier:
  name: ansible
  lint: |
    set -e
    yamllint .

