---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Example assertion
    uri:
      url: "http://127.0.0.1:3000"
      status_code: 200
  - name:
    include_role:
      name: pg-promise
