---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all

  tasks:
  - name: test app
    uri:
      url: "{{ server_name }}"
      status_code: 404 # 200 later
    register: result_http
 
  - name: show content of test
    debug: var=result_http.stdout
