---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all

  tasks:
  - name: test app
    uri:
      url: "http://localhost:80"
      status_code: 200 # maybe 404
    register: result_http
 
  - name: show content of test
    debug: var=result_http.stdout
