---
# tasks to clone repo
- name: clone frontend repo
  git:
    repo: "https://{{ gituser }}:{{ gitpass }}@github.com/fabiokleis/pg_promise-front"
    dest: "{{ dir }}"
    force: yes
  register: git_results
  tags:
    - clone

- name: show git clone results
  debug: var=git_results.stdout
  tags:
    - clone
